### ISSUE TITLE
TypeError: util.print is not a function

### ISSUE THREAD

**Issue by finorix079** [likerRr/code4goal-resume-parser#10]
```
Please, wait 2 sec to skip warnings
textract: 'pdftotext' does not appear to be installed, so it will be unable to extract PDFs. http://www.foolabs.com/xpdf/
textract: 'drawingtotext' does not appear to be installed, so it will be unable to extract DXFs.
------------------------------------------------------------------------------------
                           Somewhere in big & cool company...                       
------------------------------------------------------------------------------------

/Users/me/Documents/GitHub/code4goal-resume-parser/src/Speakable.js:24
                return util.print(coloredOutput(this.getSpeakerOutput() + '- ' + phrase + "\n"));
                            ^

TypeError: util.print is not a function
    at SomeHR.Speakable.say (/Users/me/Documents/GitHub/code4goal-resume-parser/src/Speakable.js:24:15)
    at SomeHR.<anonymous> (/Users/me/Documents/GitHub/code4goal-resume-parser/app.js:32:12)
    at /Users/me/Documents/GitHub/code4goal-resume-parser/src/SomeHR.js:35:21
    at FSReqCallback.oncomplete (node:fs:188:23)
```

I got this right after I use the following 2 commands: 
```
npm i 
node app.js
```

Removing `util.print` seems to solve this issue.

**Comment by likerRr** [comment]
Hi! I think this is because you use newer version of node js, where `print` method already erased. You can safely replace it with [`console.log`](https://nodejs.org/dist./v10.0.0/docs/api/util.html#util_util_print_strings)
