### ISSUE TITLE
Hi I am trying to use your parser, but I am running into error

### ISSUE THREAD

**Issue by wsuphappyhour** [likerRr/code4goal-resume-parser#3]
Hi, I am trying to use your parser, but I am running into error.  Maybe you have an idea how to fix it?

HR manager:
- My stack for today are: .gitkeep, resume.html, resume.txt
Parse Boy:
- Hi, i can help you with .gitkeep, resume.html, resume.txt
(node:10520) DeprecationWarning: util.print is deprecated. Use console.log instead.
{ Error: textract does not currently extract files of type [[ application/octet-stream ]]
    at extract (I:\tools\code4goal-resume-parser\node_modules\textract\lib\extract.js:86:19)
    at I:\tools\code4goal-resume-parser\node_modules\textract\lib\index.js:9:7
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19) typeNotFound: true }
- I'm working with "resume.txt" now
- I'm working with "resume.html" now
null

Thanks!

**Comment by likerRr** [comment]
@wsuphappyhour hi! try to remove `.gitkeep` file

**Comment by wsuphappyhour** [comment]
Hi, thanks for swift replay. Your suggestion discarded errors, but one remains:

(node:3348) DeprecationWarning: util.print is deprecated. Use console.log instead.
![image](https://cloud.githubusercontent.com/assets/20355306/21141530/69d2e8ae-c146-11e6-8a9e-c45c8b44155e.png)

Thanks

**Comment by wsuphappyhour** [comment]
I also tested on Ubuntu it does not throw  same error, but output is null.
![image](https://cloud.githubusercontent.com/assets/20355306/21141781/b40937ba-c147-11e6-8fbc-1d1fbddaf9ad.png)

**Comment by likerRr** [comment]
@wsuphappyhour it's not a error, it's just a warning, so ignore it. The null output needs investigations. Sorry, but currently I have no time for this. I would thank you if you investigate the issue and make a PR

**Comment by wsuphappyhour** [comment]
Ok, thanks

**Comment by cekimy** [comment]
i meet with the same error, and find that the reason is 'download from linkedin.com response the http status 999', so error is null. sorry for my poor english.
`src/dictionary.js`
```
function download(url, callback) {
  request(url, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      callback(body);
    } else {
console.log(response.statusCode);
      callback(null, error)
    }
  });
}
```

**Comment by cekimy** [comment]
@wsuphappyhour so, just comment out or delete profiles in src/dictionary.js
```
profiles: [
]
```

**Comment by wsuphappyhour** [comment]
@cekimy Great that works, thank you so much!
Have a nice day

**Comment by rahul177** [comment]
How will i parse pdf resume

**Comment by likerRr** [comment]
@rahul177 make sure you match the [requirements](https://github.com/dbashford/textract#extraction-requirements) for extracting pdf

**Comment by likerRr** [comment]
@rahul177 have you had success with pdf parsing?

**Comment by rahul177** [comment]
No @likerRr

**Comment by rahul177** [comment]
I want results in xml format not in json format. Can you help me for the same ?

**Comment by likerRr** [comment]
@rahul177 the lib doesn't provide such ability. Try to find converter from json to xml on [npm](https://www.npmjs.com/search?q=json+xml).

**Comment by rahul177** [comment]
@likerRr Thanks for reply. I got the results in xml format. I used xml2js packages. 

@likerRr Can you give steps for pdf and docs parsing ? 

Thanks

**Comment by likerRr** [comment]
@rahul177 I haven't tried it. Read the docs and try to follow them, thanks

**Comment by rahul177** [comment]
@likerRr Success with pdf parsing. Steps: 
i) Go to link http://www.foolabs.com/xpdf/download.html
ii) Download zip 
iii) Extract it and add Path in Environment variables.

**Comment by likerRr** [comment]
@rahul177 glad to hear that!

**Comment by rahul177** [comment]
@likerRr I have one question : 
i) I want first name and last name instead of full name. How we will get the same ? 

Thanks

**Comment by rahul177** [comment]
How we will edit the dictionary.js for getting first name and last name ?

**Comment by likerRr** [comment]
Just split fullname into parts, like:
```
// es6 
const [firstname, lastName] = fullname.split(' ')
```

**Comment by venkatr123** [comment]
tnx @rahul177  pdf  #extractor how you did that one
