### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by venkatr123** [likerRr/code4goal-resume-parser#8]
For Different Formats Type Resumes like doc , pdf ....etc i'am getting error as below 

{ Error: Error for type: [[ application/pdf ]], file: [[ d:\code4goal-resume-parser-master/public/2016_JRM_Resume.pdf ]], extractor for type exists, but failed to initialize. Message: INFO: 'pdftotext' does not appear to be installed, so textract will be unable to extract PDFs.
    at extract (d:\code4goal-resume-parser-master\node_modules\textract\lib\extract.js:147:15)
    at Timeout._onTimeout (d:\code4goal-resume-parser-master\node_modules\textract\lib\extract.js:155:7)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5) typeNotFound: true }
Error: antiword read of file named [[ Abhilash_Reddy - Copy.doc ]] failed: Error: Command failed: antiword -m UTF-8.txt "d:\code4goal-resume-parser-master/public/Abhilash_Reddy - Copy.doc"
'antiword' is not recognized as an internal or external command,
operable program or batch file.

Is there any extractor for all formats

**Comment by likerRr** [comment]
Not sure. Moreover part of them could be out of date because `code4goal-resume-parser` itself didn't receive any updates for a long time. Sorry

**Comment by nrsharma11** [comment]
I have resolved the issue related to "pdftotext" but I am still facing issue "antiword read of file named".
Can you please suggest or help in this regards.
Thanks in advance.

**Comment by likerRr** [comment]
Great to hear! Can you send a PR with a fix?
Do you have any issues with other `doc` files? Or only with that one?

**Comment by nrsharma11** [comment]
To resolve error "pdftotext" I have downloaded the xpdf tools from [here](https://www.xpdfreader.com/download.html). Copied the pdftotext.exe in windows folder.

Yes I am facing the issue with all the doc files, it keep saying "antiword read of file named" BUT interestingly when I save the same file as ".docx" extention then it processed and I got the results. So may be there is something to do with the doc files.

I am also interested to have linked in profile based on public profile url, I tried but I am not getting results it shows blank nodes in json, please have a look below
`"linkedin": {
        "positions": {
            "past": [
            ],
            "current": {
                "title": "",
                "company": "",
                "description": "",
                "period": ""
            }
        },
        "languages": [
        ],
        "skills": [
        ],
        "educations": [
        ],
        "volunteering": [
        ],
        "volunteeringOpportunities": [
        ]
    }`

**Comment by likerRr** [comment]
Since the parser was made, linked's html or api could change. Sorry, I don't support this project for now and can't have a look. There is a [fork](https://github.com/perminder-klair/resume-parser) of my project with lots of issues fixed. Can you try it and see if your issues are fixed?

**Comment by nrsharma11** [comment]
Okay. Thanks for your reply.

**Comment by fadiajabeen** [comment]
I placed pdftotext.exe in root folder i.e. from where app.js file is being run, and now its working.
